{% set name = "PyMca5" %}
{% set version = "5.9.4" %}

package:
  name: pymca
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: e8a6f6f19e939695734bc95255b65a895caf17d8561eac74d3077561e5eb1026

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - fisx >=1.1.6
    - h5py
    - numpy
    - pip
    - python
    - cython
    - setuptools
  run:
    - fisx >=1.1.6
    - h5py
    - matplotlib-base >1.0
    - python

test:
  imports:
    - PyMca5
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pymca.sourceforge.net
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Mapping and X-Ray Fluorescence Analysis
  doc_url: http://www.silx.org/doc/PyMca/latest/tutorials.html

extra:
  recipe-maintainers:
    - tschoonj
