appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: TbMTVMjAttpdNZNF/KSabaNdelM3DcmTobj/WMoXpOJ24emDDJA1YBwF9GRFIuhP7Livn4r1re1Or1s1gURTUz8tqTwC9LOI3ShwuvBfIFDbnGSLil1VEJYwgCo09qend7qVpWKcH9s+9SBtlJ9+nPukIZDrUosA+PYVbrQkI/zVxSmCP+MN8x5Ceip0A9a+vlIDxHXGY58hJ9a4+cacQ6jdRxho8McUMfX7oD/BNbxvJrIKhlE+kouLBZKU9K60/MyDDktHeLw2T447CBBHXBVOAblXb6YCtyWtCdcMwtUCxjFybjmLsKT4ASR/wxzDmLpKTvuYG8hkg+7Y2rknryarmDea6EmCHK5ijGEtjtXLfsB9exPvD4qPExn5ZrCXYfYXBd1MDOmg4jtivx7aJugcKzjvcaYU6f1piNGDkZOkx+U6u6YSKxHhvK6j26J8LWmhLqEAXFxAi8+ih1PERWM/9O1e6C7nE4RmU2B2K1AMUjgyFOKy9xV+PY2bF12oCjOiEMJQUGValF7yVsrvJLXZixYv0P5k+SodNJY6rhcKQmXKX6bCztCH5e2eOcgFu+ZWf9yDJErjh2txPcnXhbZva40G2u0x3oh/vRA6N7i06nXMy+Q017UKM4yYZkal6sTuBRxRH9DpMnLJ6H4XHfcsXeovlnyUvdjsD5eNbjU=}
